### ISSUE TITLE
Error when running button_map.sh on Mac

### ISSUE THREAD

**Issue by ronbo85** [Texacate/Visual-RetroPie-Control-Maps#3]
Thank you for all your hard work!
When I try to launch the script, I get an error, because Mac (by default) is using dash shell. The first line in the button_map.sh script is:
#/bin/bash

It should be:
#!/bin/bash
(pesky syntax errors ;)

With the "hash-bang" at the beginning of the line, the bash shell is invoked.

**Comment by Texacate** [comment]
Thanks for catching this error.
